#!/usr/bin/env perl
use strict;
use warnings;

use Bot::BasicBot::Pluggable::Module::DateTimeCalc;

my $server = shift || 'irc.perl.org';
my $port = shift || '6667';
my $channel = shift || '#bottest';

my $bot = Bot::BasicBot::Pluggable::Module::DateTimeCalc->new(
    server      => $server,
    port        => $port,
    channels    => [ $channel ],
    nick        => 'TimeBot',
    name        => 'Time Bot',
    ignore_list => [],
);

$bot->run;
